describe('Automate main functionality of saucedemo page',()=>{
  beforeEach(()=>{
    cy.visit('https://www.saucedemo.com/')
    cy.get('.login_logo')
      .should('be.visible')
      .and('have.text', 'Swag Labs')
    cy.url().should('include','https://www.saucedemo.com/')

    cy.get('[data-test="username"]')
      .type('standard_user')
    cy.get('[data-test="password"]')
      .type('secret_sauce')
    cy.get('[data-test="login-button"]')
      .click()
    cy.url().should('include','/inventory.html')   
  })
  
  it('user is redirected to the Home page and sees a list of products.',()=>{
    cy.get('[data-test="title"]')
      .should('be.visible')
      .and('have.text','Products')
    cy.contains('Sauce Labs Backpack')
      .should('be.visible')
      .and('have.text','Sauce Labs Backpack')
    cy.contains('$29.99')
      .should('be.visible')
      .and('contain.text',"29.99")    

  })
  it('User adds a product to the cart.',()=>{
    cy.contains('Sauce Labs Bolt T-Shirt')
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text','Sauce Labs Bolt T-Shirt')
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
      .click()
    cy.get('[data-test="remove-sauce-labs-bolt-t-shirt"]')
      .should('be.visible')
      .and('have.text','Remove')
    cy.get('[data-test="shopping-cart-link"]').scrollIntoView()
    cy.get('[data-test="shopping-cart-badge"]')
      .should('be.visible')
      .and('have.text','1')


  })
  it('User successfully redirect to checkout page',()=>{
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
      .click()
    cy.get('[data-test="shopping-cart-link"]')
      .click()
    cy.contains('Your Cart')
      .should('be.visible')
      .and('have.text','Your Cart')
    cy.contains('Sauce Labs Bolt T-Shirt')
      .should('be.visible')
      .and('have.text','Sauce Labs Bolt T-Shirt')
    cy.contains('Remove')
      .should('be.visible')
    cy.get('[data-test="checkout"]')
      .should('be.visible')
      .and('have.text','Checkout')

    cy.url().should('include','/cart.html')

  })
  it('User successfully checkout',()=>{
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]')
      .click()
    cy.get('[data-test="shopping-cart-link"]').scrollIntoView().click()
    cy.get('[data-test="checkout"]')
      .should('be.visible')
      .click()
      
    cy.get('[data-test="firstName"]')
      .type('Enea')
    cy.get('[data-test="lastName"]')
      .type('Ntilka')
    cy.get('[data-test="postalCode"]')
      .type('90028')
    cy.url().should('include','/checkout-step-one.html')  
    cy.get('[data-test="continue"]')
      .should('be.visible')
      .click()
    cy.contains('Payment Information')
      .should('be.visible')
      .parent()
      .should('contain','SauceCard #31337')
    cy.contains('Shipping Information')
      .should('be.visible')
      .parent()
      .should('contain','Free Pony Express Delivery!')
    cy.contains('Price Total').should('be.visible')
    cy.get('[data-test="subtotal-label"]')
      .should('contain.text','$15.99')
    cy.get('[data-test="tax-label"]').should('contain.text','$1.28')
    cy.get('[data-test="total-label"]').should('contain.text','$17.27')
    cy.url().should('include','/checkout-step-two.html')
    cy.get('[data-test="finish"]')
      .should('be.visible')
      .click()
    cy.get('[data-test="complete-header"]').should('be.visible').and('have.text','Thank you for your order!')
    cy.get('[data-test="back-to-products"]').click()
    cy.url().should('include','/inventory.html')  
    

    
  })
  
  
})